### ISSUE TITLE
sledge config using vanilla bert instead of sci-bert?

### ISSUE THREAD

**Issue by Santosh-Gupta** [Georgetown-IR-Lab/covid-neural-ir#2]
I was looking at the config for Sledge

https://github.com/Georgetown-IR-Lab/OpenNIR/blob/master/config/sledge/_dir

It looks like it's using vanilla bert instead of scibert?

>../vanilla_bert

I've been looking through the code, it seems that vanilla bert refers to a different ranker
https://github.com/Georgetown-IR-Lab/OpenNIR/blob/663d2298ab452622e01bd249b7ad8e6b53b6863c/README.md#rankers

https://arxiv.org/abs/1810.04805

**Comment by seanmacavaney** [comment]
nope, it uses the SciBERT weights: https://github.com/Georgetown-IR-Lab/OpenNIR/blob/master/config/sledge/_dir#L7

**Comment by Santosh-Gupta** [comment]
ah, I interpreted that is it was using sciberts vocab only.
