### ISSUE TITLE
Error running evaluation on trec-covid

### ISSUE THREAD

**Issue by HangCui0510** [Georgetown-IR-Lab/covid-neural-ir#3]
<img width="438" alt="Screen Shot 2020-07-15 at 8 11 02 PM" src="https://user-images.githubusercontent.com/64120158/87612118-b0850f80-c6d7-11ea-8866-59fb756816ce.png">
<img width="1269" alt="Screen Shot 2020-07-15 at 8 11 20 PM" src="https://user-images.githubusercontent.com/64120158/87612125-b4b12d00-c6d7-11ea-83eb-b161734d2f2f.png">

**Comment by seanmacavaney** [comment]
Can you try again after re-pulling OpenNIR? It looks like it was due to a copy-paste error from an unrelated change. It was expecting the dev.msrun file to be there, even though the configuration specified that the msrun files should be ignored.

**Comment by HangCui0510** [comment]
@seanmacavaney I got a new error
<img width="526" alt="Screen Shot 2020-07-15 at 10 05 59 PM" src="https://user-images.githubusercontent.com/64120158/87618315-8cc9c580-c6e7-11ea-8359-e808e97384f5.png">
<img width="1123" alt="Screen Shot 2020-07-15 at 10 05 40 PM" src="https://user-images.githubusercontent.com/64120158/87618322-8e938900-c6e7-11ea-9fde-eb266b87b51e.png">

**Comment by seanmacavaney** [comment]
I think it would be helpful to know if the problem is something with the data fetching or elsewhere. Can you check the following?

```
$ wc -l ~/data/onir/datasets/msmarco/minidev.queries.tsv
200
$ md5sum ~/data/onir/datasets/msmarco/minidev.queries.tsv 
d12b5317d210e1b381aef966e1b6a300

$ wc -l ~/data/onir/datasets/msmarco/minidev.qrels
131
$ md5sum ~/data/onir/datasets/msmarco/minidev.qrels
f57c609ec90fbbf46de8a18a52c42639

$ wc -l ~/data/onir/datasets/msmarco/anserini.porter.minidev.runs/bm25.20.run
4000
$ md5sum ~/data/onir/datasets/msmarco/anserini.porter.minidev.runs/bm25.20.run 
b51e334673c7a049c177d8ac0ea4c146
```

**Comment by HangCui0510** [comment]
<img width="969" alt="Screen Shot 2020-07-15 at 10 57 24 PM" src="https://user-images.githubusercontent.com/64120158/87621503-ec779f00-c6ee-11ea-9260-c54494f667dd.png">

**Comment by seanmacavaney** [comment]
So it looks like the `minidev.qrels` file is empty. I'll look into why that happened, but in the meantime can you replace it with `https://macavaney.us/misc/minidev.qrels`?

It seems the Anserini BM25 run is also different (same number of lines), but I'm not super concerned about that. The scores may be off by a small amount (as has been previously reported), or they may appear in a different order due to the multithreading.

**Comment by seanmacavaney** [comment]
@HangCui0510 Did this work for you?

**Comment by HangCui0510** [comment]
do i redo this command after replacing the file? scripts/pipeline.sh config/sledge

**Comment by seanmacavaney** [comment]
Yup, it will then run with the new minidev.qrels file.

**Comment by HangCui0510** [comment]
This works, thank you!
